### ISSUE TITLE
请问一下，有什么办法可以让支付宝一直运行不被杀掉嘛？

### ISSUE THREAD

**Issue by Albert-D** [pansong291/XQuickEnergy#36]
最新的MIUI11开发版，用的magisk+太极来使用这个程序的，支付宝是play商店最新版。
现在有一个很苦恼的问题就是，无论我把支付宝放前台还是放后台，熄屏以后，过一会都会被杀（我在支付宝界面熄屏也被杀，难受）。已经给支付宝程序上锁，而且允许自启动，省电优化方式为无限制。
白天无所谓啦，毕竟没事可以看一眼，重新激活，晚上就不行了。然后问题来了，众所周知，其实偷能量就在7：00-7：30最多，白天挂一天都不及这半小时。所以急需晚上睡觉可以保持支付宝不被杀。
另，一个小建议，由于白天没啥能量偷，所以作者大大可把定时检测时间改为高峰期+低谷期模式嘛，设置两个变量，高峰时候，时间间隔短，低谷时期，白天，时间间隔长。

**Comment by abcdol** [comment]
7:00-7:30保持最低亮度亮屏不就行了 不怎么耗电

**Comment by Albert-D** [comment]
> 7:00-7:30保持最低亮度亮屏不就行了 不怎么耗电

问题是，我7点还没有起床呀。。。不过我可以试一下睡觉前就把屏幕调为常量，然后挂一晚上

**Comment by abcdol** [comment]
xposed edge定时任务

**Comment by Albert-D** [comment]
> xposed edge定时任务
貌似可行，我先试一下

**Comment by Albert-D** [comment]
> xposed edge定时任务

今天早上试了一下，xposed egde 可以打开支付宝，但是插件没法成功获取能量信息，好像晚上一晚上没有打开过手机，必须要解锁才能用，显示登录超时。
下面是部分log信息：
`2019-09-30 06:50:01  pansong291.xposed.quickenergy.hook.RpcCall, rpcCall params count: 13
2019-09-30 06:50:02  pansong291.xposed.quickenergy.hook.XposedHook, alipay.antmember.forest.h5.queryEnergyRanking, [{"av":"5","ct":"android","pageSize":20,"startPoint":"1"}]
2019-09-30 06:50:02  pansong291.xposed.quickenergy.hook.AntForestRpcCall, rpcCall_queryEnergyRanking err:
2019-09-30 06:50:02  pansong291.xposed.quickenergy.hook.AntForestRpcCall, java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at pansong291.xposed.quickenergy.hook.RpcCall.invoke(RpcCall.java:76)
	at pansong291.xposed.quickenergy.hook.AntForestRpcCall.rpcCall_queryEnergyRanking(AntForestRpcCall.java:15)
	at pansong291.xposed.quickenergy.AntForest$100000000.run(AntForest.java:63)
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [2000] : 登录超时，请重新登录。
	at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.preProcessResponse(RpcInvokerUtil.java:100044)
	at com.alipay.mobile.common.rpc.protocol.json.JsonDeserializerV2.parser(JsonDeserializerV2.java:100004)
	at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:100020)
	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:100171)
	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:100099)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy10.executeRPC(Unknown Source)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5SimpleRpcService.executeRPC(H5SimpleRpcService.java:100008)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(H5RpcUtil.java:100700)
	at java.lang.reflect.Method.invoke(Native Method)
	at me.weishu.epic.art2.EpicNative.invoke(Native Method)
	at de.robv.android.xposed.ଡଜ.ହ(SourceFile:248)
	at de.robv.android.xposed.DexposedBridge.invokeOriginalMethod(SourceFile:538)
	at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:259)
	at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil_2697606168.rpcCall(Unknown Source:121)
	... 4 more

2019-09-30 06:50:02  pansong291.xposed.quickenergy.AntForest, queryEnergyRanking err:
2019-09-30 06:50:02  pansong291.xposed.quickenergy.AntForest, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
	at org.json.JSONObject.<init>(JSONObject.java:159)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at pansong291.xposed.quickenergy.AntForest$100000000.run(AntForest.java:64)

2019-09-30 06:50:02  pansong291.xposed.quickenergy.AntForest, 线程结束0
2019-09-30 06:50:02  pansong291.xposed.quickenergy.util.Log, 暂时没有可收取的能量`

**Comment by abcdol** [comment]
你是不是没开WiFi

**Comment by Albert-D** [comment]
> 你是不是没开WiFi

咿呀，这怎么可能，WiFi我24小时都开着的，除非它自己断了，而且，我起床以后，一解锁手机，他就开始收能量了。

**Comment by abcdol** [comment]
感觉像WiFi被休眠了 或者账号状态出了问题 你把另一个日志传上来看看

**Comment by Albert-D** [comment]
> 感觉像WiFi被休眠了 或者账号状态出了问题 你把另一个日志传上来看看

继续上面的，我7点的时候起床解锁了手机，自动开启支付宝是6：50
···
2019-09-30 06:55:31  pansong291.xposed.quickenergy.AntForest, 线程结束0
2019-09-30 06:55:31  pansong291.xposed.quickenergy.util.Log, 暂时没有可收取的能量
2019-09-30 06:55:31  pansong291.xposed.quickenergy.util.Log,   收：0，帮：0
2019-09-30 06:55:34  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2019-09-30 06:55:34  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2019-09-30 06:55:34  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2019-09-30 06:55:34  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2019-09-30 06:55:34  pansong291.xposed.quickenergy.hook.XposedHook, hook onResume successfully
2019-09-30 06:55:34  pansong291.xposed.quickenergy.hook.XposedHook, hook old rpcCall err:
2019-09-30 06:55:34  pansong291.xposed.quickenergy.hook.XposedHook, hook rpcCall successfully
2019-09-30 07:00:48  pansong291.xposed.quickenergy.hook.XposedHook, com.eg.android.AlipayGphone
2019-09-30 07:00:48  pansong291.xposed.quickenergy.hook.XposedHook, hook onCreate successfully
2019-09-30 07:00:48  pansong291.xposed.quickenergy.hook.XposedHook, hook onDestroy successfully
2019-09-30 07:00:48  pansong291.xposed.quickenergy.hook.XposedHook, hook matchVersion successfully
2019-09-30 07:00:48  pansong291.xposed.quickenergy.hook.XposedHook, hook onResume successfully
2019-09-30 07:00:48  pansong291.xposed.quickenergy.hook.XposedHook, hook old rpcCall err:
2019-09-30 07:00:48  pansong291.xposed.quickenergy.hook.XposedHook, hook rpcCall successfully
2019-09-30 07:00:49  pansong291.xposed.quickenergy.hook.XposedHook, onCreate loginActivity=com.eg.android.AlipayGphone.AlipayLogin@a51d030
2019-09-30 07:00:49  pansong291.xposed.quickenergy.util.Config, immediateEffect:true
···
然后是一串读取config的代码。。。略过
···
2019-09-30 07:00:49  pansong291.xposed.quickenergy.hook.XposedHook, timer start. interval=360000
2019-09-30 07:00:49  pansong291.xposed.quickenergy.util.Log, 定时检测开始
2019-09-30 07:00:49  pansong291.xposed.quickenergy.hook.RpcCall, get Old RpcCallMethod err:
2019-09-30 07:00:49  pansong291.xposed.quickenergy.hook.RpcCall, get RpcCallMethod successfully
2019-09-30 07:00:49  pansong291.xposed.quickenergy.hook.RpcCall, rpcCall params count: 13
2019-09-30 07:00:49  pansong291.xposed.quickenergy.util.Statistics, year:2019
2019-09-30 07:00:49  pansong291.xposed.quickenergy.util.Statistics,   collected:1099
···
然后开始读我的联系人了。。。
接下来应该就是正常的收取log了。

**Comment by abcdol** [comment]
不是这个日志 是/storage/emulated/0/Android/data/pansong291.xposed.quickenergy/energy.log

**Comment by Albert-D** [comment]
> 不是这个日志 是/storage/emulated/0/Android/data/pansong291.xposed.quickenergy/energy.log

这个日记没啥用呀
`2019-09-30 01:00:04  暂时没有可收取的能量
2019-09-30 01:00:04    收：0，帮：0
2019-09-30 06:50:01  定时检测开始
2019-09-30 06:50:02  暂时没有可收取的能量
2019-09-30 06:50:02    收：0，帮：0
2019-09-30 06:55:30  定时检测开始
2019-09-30 06:55:31  暂时没有可收取的能量
2019-09-30 06:55:31    收：0，帮：0
2019-09-30 07:00:49  定时检测开始
2019-09-30 07:00:52  进入【******】的蚂蚁森林
2019-09-30 07:00:53  小鸡在挨饿
2019-09-30 07:00:53  喂鸡饲料不足
2019-09-30 07:00:53  进入【************】的蚂蚁森林
2019-09-30 07:00:53  进入【**************】的蚂蚁森林
2019-09-30 07:00:53  182秒后尝试收取能量`

**Comment by abcdol** [comment]
你的检测间隔太长了 另外06.00-07.00没有能量产生 因为你一点扫描过一次没有能量 所以6.50肯定不会有能量 软件没出问题 你明天试试7.10分打开 7.10之前日志应该也是正常的

**Comment by Albert-D** [comment]
6min都长嘛？那好，我下次改成2min。但是一点扫过一次没有，不代表6点50没有吧，那个时候已经刷新能量了，7点开始就是高峰期了，就算当时没有能量刷新，也会有xxmin后收取能量的提示的，。根据运行日记，那时候是登录有问题才刷不出来的。另外，就是一点开始，支付宝就被后台杀了，我觉得是miui的休眠做的太好了，甚至可能和我的手环联动，知道我睡觉了，然后就开始杀后台。

**Comment by abcdol** [comment]
7点之前不产能量 所有能量都在7.00以后 我觉得最好是6.50关闭WiFi再开启WiFi开启最低亮度保持亮屏

**Comment by abcdol** [comment]
目前这个版本有问题 等等124吧 我还在用120

**Comment by moeshin** [comment]
1.2.4，MIUI11，Android 10，省电策略我设置无限制，晚上熄屏数据联网，早上起来支付宝没被杀掉，但是还是没有偷到能量，登录超时。

```
2019-10-02 07:19:13  pansong291.xposed.quickenergy.AntForest, 线程结束0
2019-10-02 07:19:13  pansong291.xposed.quickenergy.util.Log, 暂时没有可收取的能量
2019-10-02 07:19:13  pansong291.xposed.quickenergy.util.Log,   收：0，帮：0
2019-10-02 07:21:11  pansong291.xposed.quickenergy.util.Log, 定时检测开始
2019-10-02 07:21:11  pansong291.xposed.quickenergy.hook.RpcCall, rpcCall params count: 13
2019-10-02 07:21:11  pansong291.xposed.quickenergy.hook.RpcCall, rpcCall params count: 13
2019-10-02 07:21:11  pansong291.xposed.quickenergy.hook.XposedHook, alipay.antmember.forest.h5.queryNextAction, [{"userId":""}]
2019-10-02 07:21:11  pansong291.xposed.quickenergy.hook.AntForestRpcCall, rpcCall_queryNextAction err:
2019-10-02 07:21:11  pansong291.xposed.quickenergy.hook.AntForestRpcCall, java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at pansong291.xposed.quickenergy.hook.RpcCall.invoke(RpcCall.java:76)
	at pansong291.xposed.quickenergy.hook.AntForestRpcCall.rpcCall_queryNextAction(AntForestRpcCall.java:30)
	at pansong291.xposed.quickenergy.AntForest$100000001.run(AntForest.java:575)
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [2000] : 登录超时，请重新登录。
	at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.preProcessResponse(RpcInvokerUtil.java:100044)
	at com.alipay.mobile.common.rpc.protocol.json.JsonDeserializerV2.parser(JsonDeserializerV2.java:100004)
	at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:100020)
	at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:100171)
	at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:100099)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.executeRPC(Unknown Source)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5SimpleRpcService.executeRPC(H5SimpleRpcService.java:100008)
	at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(H5RpcUtil.java:100700)
	at EdHooker_.hook(Unknown Source:329)
	... 4 more

2019-10-02 07:21:11  pansong291.xposed.quickenergy.AntForest, canCollectSelfEnergy err:
2019-10-02 07:21:11  pansong291.xposed.quickenergy.AntForest, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:164)
	at org.json.JSONObject.<init>(JSONObject.java:181)
	at pansong291.xposed.quickenergy.AntForest.canCollectSelfEnergy(AntForest.java:104)
	at pansong291.xposed.quickenergy.AntForest.access$1000017(Unknown Source:4)
	at pansong291.xposed.quickenergy.AntForest$100000001.run(AntForest.java:577)
```

**Comment by klever1988** [comment]
我分享一下我的几个设定吧，到目前为止一直很完美。
1， 省电策略->支付宝->无限制
2，安全中心->优化加速->锁定支付宝
3，进程锁->支付宝->永恒锁， https://github.com/xiaoxinwangluo/android_xposedapp_eternalprocessxposed
4，支付宝->收钱提醒&增强模式->开启
5，无障碍->支付宝语音权限助手->开启

第5很重要，有效防止支付宝被休眠！

**Comment by Albert-D** [comment]
> 我分享一下我的几个设定吧，到目前为止一直很完美。
> 1， 省电策略->支付宝->无限制
> 2，安全中心->优化加速->锁定支付宝
> 3，进程锁->支付宝->永恒锁， https://github.com/xiaoxinwangluo/android_xposedapp_eternalprocessxposed
> 4，支付宝->收钱提醒&增强模式->开启
> 5，无障碍->支付宝语音权限助手->开启
> 
> 第5很重要，有效防止支付宝被休眠！

我试过永恒锁，感觉有点猛，再也杀不掉进程了。。。我现在，去开发者选项打开充电不关闭屏幕，然后每天晚上就插着充电亮屏，感觉也还可以。

**Comment by 122cygf** [comment]
你试试给支付宝挂上游戏模式，然后点息屏挂机

**Comment by Rakau** [comment]
> 我分享一下我的几个设定吧，到目前为止一直很完美。
> 1， 省电策略->支付宝->无限制
> 2，安全中心->优化加速->锁定支付宝
> 3，进程锁->支付宝->永恒锁， https://github.com/xiaoxinwangluo/android_xposedapp_eternalprocessxposed
> 4，支付宝->收钱提醒&增强模式->开启
> 5，无障碍->支付宝语音权限助手->开启
> 
> 第5很重要，有效防止支付宝被休眠！

永恒锁很实用!

**Comment by Albert-D** [comment]
采用终极大招，问题可以终结了，利用xposed edge pro来录制手势解锁手机（如果手机不用密码就更简单了，直接解锁就行）

用xposed edge设定一个6:55的定时计划，计划内容是唤醒手机，然后利用录制手势解锁（不设密码手机这步可以直接用解锁指令代替），最后打开支付宝就行。
具体就是，定时任务->保存的多重任务：
1）唤醒
2）延时1000ms
3）注入手势
4）延时xxxms
5）打开支付宝
这里注入手势前插入了延时，不然可能会无法激发手势操作，具体延迟时间可以自己试试。

专治一切前台销毁，登录失败问题。

这样可以保证7点多的走路能量一定可以偷到，至于白天。。。随缘吧，反正偷一天也赶不上这一个小时的😁

**Comment by Rakau** [comment]
> 采用终极大招，问题可以终结了，利用xposed edge pro来录制手势解锁手机（如果手机不用密码就更简单了，直接解锁就行）
> 
> 用xposed edge设定一个6:55的定时计划，计划内容是唤醒手机，然后利用录制手势解锁（不设密码手机这步可以直接用解锁指令代替），最后打开支付宝就行。
> 具体就是，定时任务->保存的多重任务：
> 1）唤醒
> 2）延时1000ms
> 3）注入手势
> 4）延时xxxms
> 5）打开支付宝
> 这里注入手势前插入了延时，不然可能会无法激发手势操作，具体延迟时间可以自己试试。
> 
> 专治一切前台销毁，登录失败问题。
> 
> 这样可以保证7点多的走路能量一定可以偷到，至于白天。。。随缘吧，反正偷一天也赶不上这一个小时的😁

这个有点麻烦,永恒锁直接解决

**Comment by Albert-D** [comment]
> 
> 这个有点麻烦,永恒锁直接解决

我的永恒锁也没有用，我自己都杀不死后台，但是miui11一样可以杀掉，或者说一种保护机制吧，锁屏久了，需要解锁一下重新点开支付宝才能正常。我基本所有方法都试过，所以才说这是终极大招呀，可以说是没有办法的办法吧。

**Comment by Rakau** [comment]
看最新的反馈，那里我写了新的方法

Albert-D <notifications@github.com> 于 2019年10月17日周四 12:37写道：

**Comment by abcdol** [comment]
永恒锁真的没必要 0.30-7.00基本偷不到能量 留一晚上后台唤醒白白费电 稍微学学edge不好吗

**Comment by 168308711q** [comment]
> 你试试给支付宝挂上游戏模式，然后点息屏挂机

哈哈哈，省电策略不会关闭wifi嘛

**Comment by Albert-D** [comment]
> > 你试试给支付宝挂上游戏模式，然后点息屏挂机
> 
> 哈哈哈，省电策略不会关闭wifi嘛

其实我觉得还是edge这种方式更好，毕竟我们就是要保证7：00-7：40的高峰期是在线的就行，你挂一晚上没有意义。我现在已经可以保证每天是100%可以偷掉所有步行的产生的能量了，很稳！

**Comment by vvlinus** [comment]
> 采用终极大招，问题可以终结了，利用xposed edge pro来录制手势解锁手机（如果手机不用密码就更简单了，直接解锁就行）
> 
> 用xposed edge设定一个6:55的定时计划，计划内容是唤醒手机，然后利用录制手势解锁（不设密码手机这步可以直接用解锁指令代替），最后打开支付宝就行。
> 具体就是，定时任务->保存的多重任务：
> 1）唤醒
> 2）延时1000ms
> 3）注入手势
> 4）延时xxxms
> 5）打开支付宝
> 这里注入手势前插入了延时，不然可能会无法激发手势操作，具体延迟时间可以自己试试。
> 
> 专治一切前台销毁，登录失败问题。
> 
> 这样可以保证7点多的走路能量一定可以偷到，至于白天。。。随缘吧，反正偷一天也赶不上这一个小时的

找到个代替你这个的方案：
用Edge新建
应用状态触发 -> 支付宝 -> 结束 -> 多重动作 -> 添加1唤醒，2延时3000毫秒，3打开应用支付宝。

意思就是每次支付宝后台被干后时触发亮屏，延时三秒后打开支付宝。已经测试即使有指纹密码锁也能稳定不掉。前提是用了进程锁加永恒锁，以及在后台应用切换页面锁定。

缺点是偶尔解锁后看到的是支付宝，或者正在使用时可能会跳转到支付宝，但非常少见，一个月可能会有两次，另外就是感觉有点耗电。

**Comment by 168308711q** [comment]
之前用过edge，现在用的是1.27雨季版添加为自启动后就好了，什么都不用设置

**Comment by 168308711q** [comment]
edge是凌晨为了省电定时开关养鸡时用的，每小时启动一次后冻结应用

**Comment by 168308711q** [comment]
至于为什么自启动又能用了，可能是改变了小米智能省电策略的生物钟，毕竟ZFB现在是耗电大户啊杀不得

**Comment by Albert-D** [comment]
> 
> 找到个代替你这个的方案：
> 用Edge新建
> 应用状态触发 -> 支付宝 -> 结束 -> 多重动作 -> 添加1唤醒，2延时3000毫秒，3打开应用支付宝。
> 
> 意思就是每次支付宝后台被干后时触发亮屏，延时三秒后打开支付宝。已经测试即使有指纹密码锁也能稳定不掉。前提是用了进程锁加永恒锁，以及在后台应用切换页面锁定。
> 
> 缺点是偶尔解锁后看到的是支付宝，或者正在使用时可能会跳转到支付宝，但非常少见，一个月可能会有两次，另外就是感觉有点耗电。

把支付宝常驻后台其实并不是最优解，耗电大户，白天的时候，只要一两个小时唤醒一次就够了，因为白天几乎没有啥能量偷，我这个方案的优点是，只有在早上可以偷最多能量的时候才启动支付宝，其他时候后台爱杀杀，反倒省电。

**Comment by 122cygf** [comment]
我刚才在xquickenergy翻了源码，然后发现xq的保活方式是支付宝前台服务死了之后就启动一个支付宝服务。
在xposededge里添加应用状态触发-支付宝结束-多重动作-延时1000(这个你随意)-shell命令:
am startservice com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService
有root最好用root权限，没有就用系统权限，我这死了两秒马上复活

**Comment by 168308711q** [comment]
> 我刚才在xquickenergy翻了源码，然后发现xq的保活方式是支付宝前台服务死了之后就启动一个支付宝服务。
> 在xposededge里添加应用状态触发-支付宝结束-多重动作-延时1000(这个你随意)-shell命令:
> am startservice com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService
> 有root最好用root权限，没有就用系统权限，我这死了两秒马上复活
> 也不会在你玩游戏或者做别的的时候支付宝突然启动弹出来

自启动+重启服务这个没问题，问题是长时间使用会出现超时/2000，所以建议添加个定时重启服务而不是前台死后重开

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
