### ISSUE TITLE
凌晨出现登录超时

### ISSUE THREAD

**Issue by zkzqzzz** [pansong291/XQuickEnergy#50]
凌晨的时候会出现这个错，然后就不能用了
Caused by: com.alipay.mobile.common.rpc.RpcException: RPCException: [2000] : 登录超时，请重新登录。 	
           at com.alipay.mobile.common.rpc.util.RpcInvokerUtil.preProcessResponse(RpcInvokerUtil.java:100044) 	
           at com.alipay.mobile.common.rpc.protocol.json.JsonDeserializerV2.parser(JsonDeserializerV2.java:100004) 	
           at com.alipay.mobile.common.rpc.RpcInvoker.a(RpcInvoker.java:100020) 	
           at com.alipay.mobile.common.rpc.RpcInvoker.invoke(RpcInvoker.java:100171) 	
           at com.alipay.mobile.common.rpc.RpcInvocationHandler.invoke(RpcInvocationHandler.java:100099) 	
           at java.lang.reflect.Proxy.invoke(Proxy.java:813) 	
           at $Proxy13.executeRPC(Unknown Source) 	
           at com.alipay.mobile.nebulaappproxy.api.rpc.H5SimpleRpcService.executeRPC(H5SimpleRpcService.java:100008) 	
           at com.alipay.mobile.nebulaappproxy.api.rpc.H5RpcUtil.rpcCall(H5RpcUtil.java:100700) 	
           ... 6 more

**Comment by pansong291** [comment]
请重新登录

**Comment by zkzqzzz** [comment]
但是我的支付宝并没有退出，重新打开一次支付宝又可以了

**Comment by Albert-D** [comment]
我也是这样子的，锁屏了就会这样，可能是一种保护机制？所以晚上只能够，插着充电然后亮屏一晚上。

**Comment by Rakau** [comment]
> 我也是这样子的，锁屏了就会这样，可能是一种保护机制？所以晚上只能够，插着充电然后亮屏一晚上。

不怕烧屏吗?还是LCD的

**Comment by Albert-D** [comment]
> > 我也是这样子的，锁屏了就会这样，可能是一种保护机制？所以晚上只能够，插着充电然后亮屏一晚上。
> 
> 不怕烧屏吗?还是LCD的

LCD永不为奴，哈哈哈哈，我是mix2s，基本最后一代的lcd手机了

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
