### ISSUE TITLE
能正常激活，但是所有收取数据都为0

### ISSUE THREAD

**Issue by moonstrike1** [pansong291/XQuickEnergy#77]
手机：1加3
系统：安卓8.0 
支付宝版本10.1.65 
XQE版本 1.2.7 
框架：XP和太极都用过，目前是太极
问题：最早的XQE版本可用，自从1.2.X版本以后，能激活，开支付宝也能在通知栏带起XQE通知，但是所有数据都一直为0，点开森林界面也没有任何反应（用最早的版本进森林会显示收取的情况）
[runtime.log](https://github.com/pansong291/XQuickEnergy/files/3759604/runtime.log)
[simple.log](https://github.com/pansong291/XQuickEnergy/files/3759605/simple.log)

**Comment by moonstrike1** [comment]
看了看，频繁出错显示的都是这一段，这个是什么原因啊？
2019-10-23 08:59:03  pansong291.xposed.quickenergy.hook.RpcCall, get Old RpcCallMethod err:
2019-10-23 08:59:03  pansong291.xposed.quickenergy.hook.RpcCall, get RpcCallMethod err:
2019-10-23 08:59:03  pansong291.xposed.quickenergy.hook.AntForestRpcCall, rpcCall_queryNextAction err:
2019-10-23 08:59:03  pansong291.xposed.quickenergy.hook.AntForestRpcCall, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Method.getParameterTypes()' on a null object reference
	at pansong291.xposed.quickenergy.hook.RpcCall.invoke(RpcCall.java:52)
	at pansong291.xposed.quickenergy.hook.AntForestRpcCall.rpcCall_queryNextAction(AntForestRpcCall.java:29)
	at pansong291.xposed.quickenergy.AntForest.canCollectSelfEnergy(AntForest.java:88)
	at pansong291.xposed.quickenergy.AntForest.access$1000011(Unknown Source:0)
	at pansong291.xposed.quickenergy.AntForest$100000000.run(AntForest.java:530)

**Comment by AlfieLi** [comment]
遇到同样的问题，求解决方案

**Comment by AlfieLi** [comment]
手机：华为荣耀8x
Android版本：9
EMUI版本：9.1
支付宝版本：10.1.35 （Virtual Xposed）

报错信息：Attempt to invoke interface method 'android.os.Bundle com.alipay.mobile.h5container.api.H5Page.getParams()' on a null object reference

**Comment by AlfieLi** [comment]
@pansong291 能否帮忙看下问题？

**Comment by ZhouHoubin** [comment]
> @pansong291 能否帮忙看下问题？

动态代理 H5PageImpl

**Comment by AlfieLi** [comment]
> > @pansong291 能否帮忙看下问题？
> 
> 动态代理 H5PageImpl

请问如何解决这个问题？

**Comment by ZhouHoubin** [comment]
> > > @pansong291 能否帮忙看下问题？
> > 
> > 
> > 动态代理 H5PageImpl
> 
> 请问如何解决这个问题？

rpcCall 的 H5Page 改成动态代理，非空就行

**Comment by AlfieLi** [comment]
> > > > @pansong291 能否帮忙看下问题？
> > > 
> > > 
> > > 动态代理 H5PageImpl
> > 
> > 
> > 请问如何解决这个问题？
> 
> rpcCall 的 H5Page 改成动态代理，非空就行

您是说用动态代理的方式重新实现原来的代码？

**Comment by ZhouHoubin** [comment]
> > > > > @pansong291 能否帮忙看下问题？
> > > > 
> > > > 
> > > > 动态代理 H5PageImpl
> > > 
> > > 
> > > 请问如何解决这个问题？
> > 
> > 
> > rpcCall 的 H5Page 改成动态代理，非空就行
> 
> 您是说用动态代理的方式重新实现原来的代码？

Object h5Page = Proxy.newProxyInstance(mainHook.getClassLoader(), mainHook.load("com.alipay.mobile.nebulacore.core.H5PageImpl").getInterfaces(), new H5PageProxy());  H5PageProxy 里面不需要做任何实现

**Comment by AlfieLi** [comment]
> > > > > > @pansong291 能否帮忙看下问题？
> > > > > 
> > > > > 
> > > > > 动态代理 H5PageImpl
> > > > 
> > > > 
> > > > 请问如何解决这个问题？
> > > 
> > > 
> > > rpcCall 的 H5Page 改成动态代理，非空就行
> > 
> > 
> > 您是说用动态代理的方式重新实现原来的代码？
> 
> Object h5Page = Proxy.newProxyInstance(mainHook.getClassLoader(), mainHook.load("com.alipay.mobile.nebulacore.core.H5PageImpl").getInterfaces(), new H5PageProxy()); H5PageProxy 里面不需要做任何实现

兄弟，非常感谢，是在哪个文件里面改呢？

**Comment by moonstrike1** [comment]
感谢了，但是没有太看明白，这是改动是代码层面的？还是配置层面的？

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
